/**
 * The Rhythm screen (roadmap 2.13, 3.21/5.21, REQ-3.9.1-adjacent, REQ-3.6.2;
 * redesigned as a tap instrument roadmap UI-14, 2026-08-12 UI audit).
 * A mode switch over two drills, not a new nav destination — `app/shell/Shell.tsx`
 * is owned by another session this round and cannot take a new route, so this
 * is the option that ships today (see roadmap 3.21's own note):
 *
 *  - **"Sight-reading mode"** (the original drill, unchanged, still the
 *    default so every existing test and habit keeps working): the pattern is
 *    engraved on the staff for the whole run and the audio is deliberately
 *    silenced — reading notation while tapping a silent click, i.e. rhythm
 *    SIGHT-READING. Lives in `useRhythmDrill.ts`.
 *  - **"Clap-back mode"** (new): the pattern is HEARD, never shown, then
 *    tapped back from memory once playback ends — real call-and-response,
 *    REQ-3.6.2. Lives in `RhythmClapback.tsx`/`useClapbackDrill.ts`, entirely
 *    separate from the sight-read view below (it never imports
 *    `ExerciseScore`, on purpose).
 *
 * The two mode buttons are deliberately NOT labelled with the word "tap"
 * (`e2e/metronome-drills.spec.ts`, which this file may not edit, looks up
 * the drill's own Tap pad with a bare `{ name: 'Tap' }` — Playwright's
 * default name match is substring, so any mode label containing "tap" would
 * make that lookup ambiguous). The tap pad's own accessible name (below)
 * deliberately starts with "Tap" to keep matching that same lookup, which
 * this task's brief requires stay unbroken.
 *
 * ## The tap pad (roadmap UI-14)
 *
 * The 2026-08-12 UI audit's finding: idle was five controls in a void, and
 * running relegated the one control the learner hits repeatedly — Tap — to a
 * minimum-size corner button under a wall of plain-text status. The redesign
 * makes the pad the primary running-state surface: full-width, glance-sized
 * count, a flash on every hit. It is a plain `<button>` (not a div with a
 * click handler) so it stays keyboard-reachable and gets a real accessible
 * name for free; Space bar tapping is unchanged, still driven entirely by
 * `useRhythmDrill.ts`'s own window-level listener (never touched here — that
 * timing logic is correctness-critical and out of this task's file list).
 *
 * This file only renders the chosen mode; pattern generation, playback and
 * grading all live in the two drills' own hooks behind it.
 */
import type { ConnectMidi } from '@app/practice/useMidiConnection.ts'
import type { FrameDriver } from '@app/practice/useTransportLoop.ts'
import { ExerciseScore } from '@app/sightreading/ExerciseScore.tsx'
import { Icon } from '@app/ui/Icon.tsx'
import type { ScoreChrome } from '@app/score/engraver.ts'
import type { AudioOutput, Clock, MidiInput, Rng } from '@core/ports/index.ts'
import type { TapVerdict } from '@core/rhythm/tapClassifier.ts'
import { useId, useState } from 'react'
import { RhythmClapback } from './RhythmClapback.tsx'
import { useRhythmDrill } from './useRhythmDrill.ts'

export type RhythmScreenProps = {
  /** Injection seams for tests; each defaults to the real browser adapter. */
  readonly clock?: Clock
  readonly rng?: Rng
  readonly audioOutput?: AudioOutput
  readonly midiInput?: MidiInput
  readonly connectMidi?: ConnectMidi
  readonly frameDriver?: FrameDriver
}

const COMPLEXITIES = [1, 2, 3, 4, 5] as const
type Complexity = (typeof COMPLEXITIES)[number]
const MIN_COMPLEXITY: Complexity = 1
const MAX_COMPLEXITY: Complexity = 5
const BARS = 4

/** 'sight-tap' (the original drill) stays the default so every existing habit
 *  and test keeps working unchanged — see the module doc. */
type RhythmMode = 'sight-tap' | 'clap-back'

/** Suppresses the engraved title/composer block (the pattern's own real title
 *  is still generated by `rhythmToScore`/`useRhythmDrill.ts` — this only
 *  stops it being drawn a SECOND time on the paper, redundant with the
 *  `.page-header` above) and tightens paper padding for the compact running
 *  stage. A stable object identity so it never forces `ScoreViewer`'s load
 *  effect to re-run — see `ExerciseScore`'s own prop doc. */
const PAPER_CHROME: ScoreChrome = { title: false, compact: true }

function stepComplexity(current: Complexity, delta: 1 | -1): Complexity {
  const next = COMPLEXITIES[COMPLEXITIES.indexOf(current) + delta]
  return next ?? current
}

function percent(fraction: number): string {
  return `${Math.round(fraction * 100)}%`
}

/**
 * Roadmap U.3: the per-tap flash's glyph, always paired with a
 * `--fb-*`-token color (never color alone, DESIGN.md rule 8). `undefined`
 * means the tap matched no onset — `tapClassifier.ts`'s "extra" case — shown
 * with the SAME '+' badge `colors.css` already documents for `--fb-extra`
 * ("+ badge — note played, none expected"), not a new glyph. 'early'/'late'
 * reuse the '‹'/'›' marks `colors.css`'s own token comments assign that exact
 * meaning to for `--fb-early`/`--fb-late`, so this introduces no new visual
 * vocabulary, only applies the vocabulary that already existed.
 */
function TapFlashGlyph({ verdict }: { readonly verdict: TapVerdict | undefined }) {
  if (verdict === 'hit') return <Icon name="check" />
  if (verdict === 'early') return <>‹</>
  if (verdict === 'late') return <>›</>
  return <>+</>
}

/**
 * Roadmap U.3 fix round (F6): the announced counterpart to `TapFlashGlyph`'s
 * `aria-hidden` badge — see `feature-rhythm.css`'s `.rhythm-tap-verdict-sr`
 * comment for why a SEPARATE region exists rather than un-hiding the badge
 * itself. Prefixed with the tap count so two consecutive taps landing the
 * same verdict (e.g. "Hit" twice in a row) still produce distinct text —
 * `role="status"` regions are only guaranteed to be re-announced when their
 * content actually changes. Empty before the first tap, so nothing is
 * announced on mount.
 */
function verdictStatusText(tapCount: number, verdict: TapVerdict | undefined): string {
  if (tapCount === 0) return ''
  const label = verdict === 'hit' ? 'Hit' : verdict === 'early' ? 'Early' : verdict === 'late' ? 'Late' : 'Extra tap'
  return `Tap ${tapCount}: ${label}`
}

const MODE_SUBTITLE: Record<RhythmMode, string> = {
  'sight-tap': 'Read the notation and tap the beat you see.',
  'clap-back': 'Listen to a phrase, then clap it back from memory.',
}

export function RhythmScreen(props: RhythmScreenProps) {
  const [mode, setMode] = useState<RhythmMode>('sight-tap')
  const [complexity, setComplexity] = useState<Complexity>(MIN_COMPLEXITY)
  const [metronomeEnabled, setMetronomeEnabled] = useState(true)
  const drill = useRhythmDrill({ ...props, complexity, bars: BARS, metronomeEnabled })
  const complexityLabelId = useId()

  return (
    <div className="page page--focus rhythm-screen">
      <header className="page-header">
        <div>
          <h1>Rhythm</h1>
          <p className="page-header-subtitle">{MODE_SUBTITLE[mode]}</p>
        </div>
      </header>

      <div className="seg-control" role="group" aria-label="Rhythm mode">
        <button
          type="button"
          className={mode === 'sight-tap' ? 'selected' : ''}
          onClick={() => setMode('sight-tap')}
        >
          Sight-reading mode
        </button>
        <button
          type="button"
          className={mode === 'clap-back' ? 'selected' : ''}
          onClick={() => setMode('clap-back')}
        >
          Clap-back mode
        </button>
      </div>

      {mode === 'clap-back' && <RhythmClapback {...props} />}

      {mode === 'sight-tap' && (
        <>
          {drill.phase === 'idle' && (
            <div className="card">
              <div className="field-row">
                <div className="field">
                  <label id={complexityLabelId}>Complexity</label>
                  <div className="stepper" role="group" aria-labelledby={complexityLabelId}>
                    <button
                      type="button"
                      aria-label="Decrease complexity"
                      disabled={complexity <= MIN_COMPLEXITY}
                      onClick={() => setComplexity((c) => stepComplexity(c, -1))}
                    >
                      <Icon name="minus" />
                    </button>
                    <span className="stepper-value" data-testid="rhythm-complexity">
                      {complexity}
                    </span>
                    <button
                      type="button"
                      aria-label="Increase complexity"
                      disabled={complexity >= MAX_COMPLEXITY}
                      onClick={() => setComplexity((c) => stepComplexity(c, 1))}
                    >
                      <Icon name="plus" />
                    </button>
                  </div>
                </div>

                <label>
                  <input
                    type="checkbox"
                    checked={metronomeEnabled}
                    onChange={(event) => setMetronomeEnabled(event.target.checked)}
                  />
                  Metronome click
                </label>
              </div>
            </div>
          )}

          {drill.phase === 'idle' && (
            <button type="button" className="btn-primary" onClick={drill.start}>
              <Icon name="play" />
              Start
            </button>
          )}

          {drill.phase === 'tapping' && drill.score !== undefined && (
            <section aria-label="Tapping" className="rhythm-stage">
              <ExerciseScore score={drill.score} chrome={PAPER_CHROME} />

              <div className="stat-group">
                <div className="stat">
                  <span className="stat-value" data-testid="rhythm-position-measure">
                    {drill.position?.measureNumber ?? '—'}
                  </span>
                  <span className="stat-label">Measure</span>
                </div>
                <div className="stat">
                  <span className="stat-value" data-testid="rhythm-position-beat">
                    {drill.position?.beat ?? '—'}
                  </span>
                  <span className="stat-label">Beat</span>
                </div>
              </div>

              <button type="button" className="rhythm-tap-pad" aria-label="Tap here — or press Space" onClick={drill.tap}>
                <span className="rhythm-tap-pad-label" role="status" data-testid="rhythm-tapping-status">
                  Tap here — or press Space
                </span>
                <span
                  className="rhythm-tap-pad-count"
                  data-testid="rhythm-tap-count"
                  aria-hidden="true"
                >
                  {drill.tapCount}
                </span>
                {drill.tapCount > 0 && (
                  <span
                    key={drill.tapCount}
                    className={`rhythm-tap-pad-flash rhythm-tap-pad-flash--${drill.lastTapVerdict ?? 'extra'}`}
                    aria-hidden="true"
                    data-testid="rhythm-tap-verdict"
                    data-verdict={drill.lastTapVerdict ?? 'extra'}
                  >
                    <TapFlashGlyph verdict={drill.lastTapVerdict} />
                  </span>
                )}
              </button>

              <p role="status" className="rhythm-tap-verdict-sr" data-testid="rhythm-tap-verdict-sr">
                {verdictStatusText(drill.tapCount, drill.lastTapVerdict)}
              </p>

              <button type="button" className="btn-ghost rhythm-stop-btn" onClick={drill.stop}>
                <Icon name="stop" />
                Stop
              </button>
            </section>
          )}

          {drill.phase === 'graded' && drill.stopOutcome === 'aborted' && (
            <section aria-label="Result">
              <p data-testid="rhythm-aborted">Stopped before any notes were graded.</p>
              <button type="button" className="btn-primary" onClick={drill.start}>
                <Icon name="play" />
                Again
              </button>
            </section>
          )}

          {drill.phase === 'graded' && drill.grade !== undefined && drill.stopOutcome !== 'aborted' && (
            <section aria-label="Result">
              {drill.stopOutcome === 'partial' && drill.partial !== undefined && (
                <p data-testid="rhythm-partial-note">
                  Stopped early — graded {drill.partial.decided} of {drill.partial.total} notes.
                </p>
              )}
              <div className="stat-group">
                <div className="stat">
                  <span className="stat-value" data-testid="rhythm-matched">
                    {drill.grade.matched}
                  </span>
                  <span className="stat-label">Matched</span>
                </div>
                <div className="stat">
                  <span className="stat-value" data-testid="rhythm-missed">
                    {drill.grade.missed}
                  </span>
                  <span className="stat-label">Missed</span>
                </div>
                <div className="stat">
                  <span className="stat-value" data-testid="rhythm-extra">
                    {drill.grade.extra}
                  </span>
                  <span className="stat-label">Extra</span>
                </div>
                <div className="stat">
                  <span className="stat-value" data-testid="rhythm-accuracy">
                    {percent(drill.grade.accuracy)}
                  </span>
                  <span className="stat-label">Accuracy</span>
                </div>
                <div className="stat">
                  <span className="stat-value" data-testid="rhythm-deviation">
                    {Math.round(drill.grade.meanAbsDeviationMs)}ms
                  </span>
                  <span className="stat-label">Mean deviation</span>
                </div>
              </div>
              <button type="button" className="btn-primary" onClick={drill.start}>
                <Icon name="play" />
                Again
              </button>
            </section>
          )}
        </>
      )}
    </div>
  )
}
